services:
  pdf-ai-app:
    build: .
    container_name: pdf-ai-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
    restart: unless-stopped
